<p align="center">
<img src="https://www.python.org/static/community_logos/python-powered-h-70x91.png?raw=true" width="100" height="">
</p>

 # **<font color="#07a8ed">Preprocesamiento de los Datos - Codificación e imputaciones</font>**

## **<font color="#07a8ed">Bibliotecas**

### **<font color="#07a8ed">Para análisis de datos**

In [21]:
import pandas as pd
import numpy as np

### **<font color="#07a8ed">Para preprocesamiento de datos**

In [22]:
import sklearn
from sklearn.preprocessing import LabelEncoder  ###Codifique las etiquetas de destino con valores entre 0 y n_classes-1
from sklearn.impute import SimpleImputer  ### imputacion simple

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder


https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer


 ## **<font color="#07a8ed">Obtención de los Datos</font>**

In [23]:
url = "https://raw.githubusercontent.com/cristiandarioortegayubro/BA/main/Datasets/banco.csv"

In [24]:
analisis = pd.read_csv(url, index_col=0)
analisis.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may       261         1     -1         0  unknown      no  
1  unknown    5   may       151         1     -1         0  unknown      no  
2  unknown    5   may        76         1     -1         0  unknown      no  
3  unknown    5   may        92         1     -1         0  unknown      no  
4  unknown    5   may       198         1     -1         0  unknown      no

In [25]:
# analisis.to_csv("bank-full.csv")

In [26]:
##analisis.job.value_counts()

In [27]:
###analisis.education.value_counts()

In [28]:
##analisis.contact.value_counts()

In [29]:
###analisis.poutcome.value_counts()

 ## **<font color="#07a8ed">Análisis Exploratorio de los Datos</font>**

In [30]:
###!pip install pandas-profiling --upgrade

In [31]:
###from ydata_profiling import ProfileReport

In [32]:
###ProfileReport(analisis)

 ### **<font color="#07a8ed">Información inicial de las variables</font>**

In [33]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 6.2+ MB


 ### **<font color="#07a8ed">Valores únicos por variable</font>**

In [34]:
analisis.age.unique()

array([58, 44, 33, 47, 35, 28, 42, 43, 41, 29, 53, 57, 51, 45, 60, 56, 32,
       25, 40, 39, 52, 46, 36, 49, 59, 37, 50, 54, 55, 48, 24, 38, 31, 30,
       27, 34, 23, 26, 61, 22, 21, 20, 66, 62, 83, 75, 67, 70, 65, 68, 64,
       69, 72, 71, 19, 76, 85, 63, 90, 82, 73, 74, 78, 80, 94, 79, 77, 86,
       95, 81, 18, 89, 84, 87, 92, 93, 88])

In [35]:
analisis.job.unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [36]:
analisis.job.value_counts()

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [37]:
analisis.marital.unique()

array(['married', 'single', 'divorced'], dtype=object)

In [38]:
analisis.education.unique()

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [39]:
analisis.default.unique()

array(['no', 'yes'], dtype=object)

In [40]:
analisis.balance.unique()

array([ 2143,    29,     2, ...,  8205, 14204, 16353])

In [41]:
analisis.housing.unique()

array(['yes', 'no'], dtype=object)

In [42]:
analisis.loan.unique()

array(['no', 'yes'], dtype=object)

In [43]:
analisis.contact.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [44]:
analisis.day.unique()

array([ 5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 19, 20, 21, 23, 26, 27, 28,
       29, 30,  2,  3,  4, 11, 17, 18, 24, 25,  1, 10, 22, 31])

In [45]:
analisis.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [46]:
analisis.duration.unique()

array([ 261,  151,   76, ..., 1298, 1246, 1556])

In [47]:
analisis.campaign.unique()

array([ 1,  2,  3,  5,  4,  6,  7,  8,  9, 10, 11, 12, 13, 19, 14, 24, 16,
       32, 18, 22, 15, 17, 25, 21, 43, 51, 63, 41, 26, 28, 55, 50, 38, 23,
       20, 29, 31, 37, 30, 46, 27, 58, 33, 35, 34, 36, 39, 44])

In [48]:
analisis.pdays.unique()

array([ -1, 151, 166,  91,  86, 143, 147,  89, 140, 176, 101, 174, 170,
       167, 195, 165, 129, 188, 196, 172, 118, 119, 104, 171, 117, 164,
       132, 131, 123, 159, 186, 111, 115, 116, 173, 178, 110, 152,  96,
       103, 150, 175, 193, 181, 185, 154, 145, 138, 126, 180, 109, 158,
       168,  97, 182, 127, 130, 194, 125, 105, 102,  26, 179,  28, 183,
       155, 112, 120, 137, 124, 187, 190, 113, 162, 134, 169, 189,   8,
       144, 191, 184, 177,   5,  99, 133,  93,  92,  10, 100, 156, 198,
       106, 153, 146, 128,   7, 121, 160, 107,  90,  27, 197, 136, 139,
       122, 157, 149, 135,  30, 114,  98, 192, 163,  34,  95, 141,  31,
       199,  94, 108,  29, 268, 247, 253, 226, 244, 239, 245, 204, 231,
       238, 258, 230, 254, 265,  71, 223, 246, 250, 266, 240, 205, 261,
       259, 241, 260, 234, 251, 225, 161, 237, 262, 248, 255, 220, 227,
       206, 224, 249, 235, 228, 263,   2, 270, 232, 252, 207, 200, 269,
       233, 256, 273, 272, 242, 264, 208, 214, 222, 271, 203, 22

In [49]:
analisis.previous.unique()

array([  0,   3,   1,   4,   2,  11,  16,   6,   5,  10,  12,   7,  18,
         9,  21,   8,  14,  15,  26,  37,  13,  25,  20,  27,  17,  23,
        38,  29,  24,  51, 275,  22,  19,  30,  58,  28,  32,  40,  55,
        35,  41])

In [50]:
analisis.poutcome.unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

 ## **<font color="#07a8ed">Reemplazo de "unknown"</font>**

In [51]:
analisis.replace({"unknown": None}, inplace=True) ### reemplazo el unknown por el None

In [52]:
analisis.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married       None      no     1506     yes   no   
4   33          None    single       None      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

  contact  day month  duration  campaign  pdays  previous poutcome deposit  
0    None    5   may       261         1     -1         0     None      no  
1    None    5   may       151         1     -1         0     None      no  
2    None    5   may        76         1     -1         0     None      no  
3    None    5   may        92         1     -1         0     None      no  
4    None    5   may       198         1     -1         0     None      no  
5    None    5   may       139         1     -1         0     None      no  
6    None    5   may       217         1     -1         0     None      no  
7    None    5   may       380         1     -1         0     None      no  
8    None    5   may        50         1     -1         0     None      no  
9    None    5   may        55         1     -1         0     None      no

In [53]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        44923 non-null  object
 2   marital    45211 non-null  object
 3   education  43354 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    32191 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   8252 non-null   object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 6.2+ MB


In [54]:
analisis.isnull().sum().sort_values(ascending=False)  ## metodo isnull para devolver los nulos en orden ascendente

poutcome     36959
contact      13020
education     1857
job            288
month            0
previous         0
pdays            0
campaign         0
duration         0
age              0
day              0
loan             0
housing          0
balance          0
default          0
marital          0
deposit          0
dtype: int64

 ## **<font color="#07a8ed">Codificación de variables categóricas</font>**

Las columnas a convertir string con LabelEncoder son:
- job
- marital
- education
- default
- housing
- loan
- contact
- poutcome


In [55]:
analisis.head(3)

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   

  contact  day month  duration  campaign  pdays  previous poutcome deposit  
0    None    5   may       261         1     -1         0     None      no  
1    None    5   may       151         1     -1         0     None      no  
2    None    5   may        76         1     -1         0     None      no

In [56]:
convertir = LabelEncoder()

In [57]:
analisis.insert(2,column="numjob",value=convertir.fit_transform(analisis.job))
analisis.insert(4,column="nummarital",value=convertir.fit_transform(analisis.marital))
analisis.insert(6,column="numeducation",value=convertir.fit_transform(analisis.education))
analisis.insert(8,column="numdefault",value=convertir.fit_transform(analisis.default))
analisis.insert(11,column="numhousing",value=convertir.fit_transform(analisis.housing))
analisis.insert(13,column="numloan",value=convertir.fit_transform(analisis.loan))
analisis.insert(15,column="numcontact",value=convertir.fit_transform(analisis.contact))
analisis.insert(23,column="numpoutcome",value=convertir.fit_transform(analisis.poutcome))

####value = convertir.fit_transform = Ajuste el codificador de etiquetas y devuelva etiquetas codificadas.

In [58]:
analisis.head(3)

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary             2   
1   44    technician       9   single           2  secondary             1   
2   33  entrepreneur       2  married           1  secondary             1   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5   may       261        1   
1      no           0       29  ...          2    5   may       151        1   
2      no           0        2  ...          2    5   may        76        1   

   pdays  previous poutcome  numpoutcome  deposit  
0     -1         0     None            3       no  
1     -1         0     None            3       no  
2     -1         0     None            3       no  

[3 rows x 25 columns]

In [59]:
analisis

age           job  numjob   marital  nummarital  education  \
0       58    management       4   married           1   tertiary   
1       44    technician       9    single           2  secondary   
2       33  entrepreneur       2   married           1  secondary   
3       47   blue-collar       1   married           1       None   
4       33          None      11    single           2       None   
...    ...           ...     ...       ...         ...        ...   
45206   51    technician       9   married           1   tertiary   
45207   71       retired       5  divorced           0    primary   
45208   72       retired       5   married           1  secondary   
45209   57   blue-collar       1   married           1  secondary   
45210   37  entrepreneur       2   married           1  secondary   

       numeducation default  numdefault  balance  ... numcontact  day month  \
0                 2      no           0     2143  ...          2    5   may   
1                 1      no           0       29  ...          2    5   may   
2                 1      no           0        2  ...          2    5   may   
3                 3      no           0     1506  ...          2    5   may   
4                 3      no           0        1  ...          2    5   may   
...             ...     ...         ...      ...  ...        ...  ...   ...   
45206             2      no           0      825  ...          0   17   nov   
45207             0      no           0     1729  ...          0   17   nov   
45208             1      no           0     5715  ...          0   17   nov   
45209             1      no           0      668  ...          1   17   nov   
45210             1      no           0     2971  ...          0   17   nov   

       duration campaign  pdays  previous poutcome  numpoutcome  deposit  
0           261        1     -1         0     None            3       no  
1           151        1     -1         0     None            3       no  
2            76        1     -1         0     None            3       no  
3            92        1     -1         0     None            3       no  
4           198        1     -1         0     None            3       no  
...         ...      ...    ...       ...      ...          ...      ...  
45206       977        3     -1         0     None            3      yes  
45207       456        2     -1         0     None            3      yes  
45208      1127        5    184         3  success            2      yes  
45209       508        4     -1         0     None            3       no  
45210       361        2    188        11    other            1       no  

[45211 rows x 25 columns]

In [60]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45211 entries, 0 to 45210
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   age           45211 non-null  int64 
 1   job           44923 non-null  object
 2   numjob        45211 non-null  int64 
 3   marital       45211 non-null  object
 4   nummarital    45211 non-null  int64 
 5   education     43354 non-null  object
 6   numeducation  45211 non-null  int64 
 7   default       45211 non-null  object
 8   numdefault    45211 non-null  int64 
 9   balance       45211 non-null  int64 
 10  housing       45211 non-null  object
 11  numhousing    45211 non-null  int64 
 12  loan          45211 non-null  object
 13  numloan       45211 non-null  int64 
 14  contact       32191 non-null  object
 15  numcontact    45211 non-null  int64 
 16  day           45211 non-null  int64 
 17  month         45211 non-null  object
 18  duration      45211 non-null  int64 
 19  campaign 

In [61]:
analisis.head(10)

age           job  numjob   marital  nummarital  education  numeducation  \
0   58    management       4   married           1   tertiary             2   
1   44    technician       9    single           2  secondary             1   
2   33  entrepreneur       2   married           1  secondary             1   
3   47   blue-collar       1   married           1       None             3   
4   33          None      11    single           2       None             3   
5   35    management       4   married           1   tertiary             2   
6   28    management       4    single           2   tertiary             2   
7   42  entrepreneur       2  divorced           0   tertiary             2   
8   58       retired       5   married           1    primary             0   
9   43    technician       9    single           2  secondary             1   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5   may       261        1   
1      no           0       29  ...          2    5   may       151        1   
2      no           0        2  ...          2    5   may        76        1   
3      no           0     1506  ...          2    5   may        92        1   
4      no           0        1  ...          2    5   may       198        1   
5      no           0      231  ...          2    5   may       139        1   
6      no           0      447  ...          2    5   may       217        1   
7     yes           1        2  ...          2    5   may       380        1   
8      no           0      121  ...          2    5   may        50        1   
9      no           0      593  ...          2    5   may        55        1   

   pdays  previous poutcome  numpoutcome  deposit  
0     -1         0     None            3       no  
1     -1         0     None            3       no  
2     -1         0     None            3       no  
3     -1         0     None            3       no  
4     -1         0     None            3       no  
5     -1         0     None            3       no  
6     -1         0     None            3       no  
7     -1         0     None            3       no  
8     -1         0     None            3       no  
9     -1         0     None            3       no  

[10 rows x 25 columns]

Y para el mes.

In [62]:
analisis.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

Se crea una función para reemplazar los nombres del mes por el número que corresponde.

In [63]:
def mes(month):
  if month == "jan":
    return int("1")
  elif month == "feb":
    return int("2")
  elif month == "mar":
    return int("3")
  elif month == "apr":
    return int("4")
  elif month == "may":
    return int("5")
  elif month == "jun":
    return int("6")
  elif month == "jul":
    return int("7")
  elif month == "aug":
    return int("8")
  elif month == "sep":
    return int("9")
  elif month == "oct":
    return int("10")
  elif month == "nov":
    return int("11")
  else:
    return int("12")

In [64]:
analisis.month = analisis.month.apply(mes)

In [65]:
analisis.month.unique()

array([ 5,  6,  7,  8, 10, 11, 12,  1,  2,  3,  4,  9])

In [66]:
analisis.head()

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary             2   
1   44    technician       9   single           2  secondary             1   
2   33  entrepreneur       2  married           1  secondary             1   
3   47   blue-collar       1  married           1       None             3   
4   33          None      11   single           2       None             3   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   
4      no           0        1  ...          2    5     5       198        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  
4     -1         0      None            3       no  

[5 rows x 25 columns]

 ## **<font color="#07a8ed">Imputación de valores faltantes</font>**

In [67]:
analisis.head(10)

age           job  numjob   marital  nummarital  education  numeducation  \
0   58    management       4   married           1   tertiary             2   
1   44    technician       9    single           2  secondary             1   
2   33  entrepreneur       2   married           1  secondary             1   
3   47   blue-collar       1   married           1       None             3   
4   33          None      11    single           2       None             3   
5   35    management       4   married           1   tertiary             2   
6   28    management       4    single           2   tertiary             2   
7   42  entrepreneur       2  divorced           0   tertiary             2   
8   58       retired       5   married           1    primary             0   
9   43    technician       9    single           2  secondary             1   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   
4      no           0        1  ...          2    5     5       198        1   
5      no           0      231  ...          2    5     5       139        1   
6      no           0      447  ...          2    5     5       217        1   
7     yes           1        2  ...          2    5     5       380        1   
8      no           0      121  ...          2    5     5        50        1   
9      no           0      593  ...          2    5     5        55        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  
4     -1         0      None            3       no  
5     -1         0      None            3       no  
6     -1         0      None            3       no  
7     -1         0      None            3       no  
8     -1         0      None            3       no  
9     -1         0      None            3       no  

[10 rows x 25 columns]

 ### **<font color="#07a8ed">Media</font>**

In [68]:
print(analisis.education[3])

None


In [69]:
analisis.numeducation[3]

3

In [70]:
analisis.head(4)

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary             2   
1   44    technician       9   single           2  secondary             1   
2   33  entrepreneur       2  married           1  secondary             1   
3   47   blue-collar       1  married           1       None             3   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  

[4 rows x 25 columns]

In [71]:
imputacion = SimpleImputer(missing_values=3, strategy="mean")  ### la imputacion simple es por la media, la mediana, el valor mas frecuente, una constante u otro valor estadistico

### missing_value= El marcador de posición para los valores faltantes.
### strategy = La estrategia de imputación:
#### Si es “media”, entonces reemplace los valores faltantes utilizando la media a lo largo de cada columna.
###media-mediana-el valor mas frecuente, constante u otro valor estadistico

In [72]:
analisis.numeducation = imputacion.fit_transform(analisis[["numeducation"]])

In [73]:
analisis.numeducation = round(analisis.numeducation,3)

In [74]:
analisis.numeducation[3]

1.149

In [75]:
analisis.head(4)

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary         2.000   
1   44    technician       9   single           2  secondary         1.000   
2   33  entrepreneur       2  married           1  secondary         1.000   
3   47   blue-collar       1  married           1       None         1.149   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  

[4 rows x 25 columns]

 ### **<font color="#07a8ed">Mediana</font>**

In [76]:
analisis.numpoutcome.unique()

array([3, 0, 1, 2])

In [77]:
analisis.numpoutcome.value_counts()

numpoutcome
3    36959
0     4901
1     1840
2     1511
Name: count, dtype: int64

In [78]:
print(analisis.poutcome[0])

None


In [79]:
analisis.numpoutcome[0]

3

In [80]:
analisis.head(4)

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary         2.000   
1   44    technician       9   single           2  secondary         1.000   
2   33  entrepreneur       2  married           1  secondary         1.000   
3   47   blue-collar       1  married           1       None         1.149   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  

[4 rows x 25 columns]

In [81]:
imputacion = SimpleImputer(missing_values=3, strategy="median")  ## imputacion simple por la mediana

In [82]:
analisis.numpoutcome = imputacion.fit_transform(analisis[["numpoutcome"]])

In [83]:
analisis.numpoutcome[4]

0.0

In [84]:
analisis.head()

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary         2.000   
1   44    technician       9   single           2  secondary         1.000   
2   33  entrepreneur       2  married           1  secondary         1.000   
3   47   blue-collar       1  married           1       None         1.149   
4   33          None      11   single           2       None         1.149   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   
4      no           0        1  ...          2    5     5       198        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None          0.0       no  
1     -1         0      None          0.0       no  
2     -1         0      None          0.0       no  
3     -1         0      None          0.0       no  
4     -1         0      None          0.0       no  

[5 rows x 25 columns]

In [85]:
analisis.numpoutcome.value_counts()

numpoutcome
0.0    41860
1.0     1840
2.0     1511
Name: count, dtype: int64

 ### **<font color="#07a8ed">Moda (el más frecuente)</font>**

In [86]:
print(analisis.contact[0])

None


In [87]:
analisis.numcontact[0]

2

In [88]:
analisis[['contact','numcontact']]

contact  numcontact
0           None           2
1           None           2
2           None           2
3           None           2
4           None           2
...          ...         ...
45206   cellular           0
45207   cellular           0
45208   cellular           0
45209  telephone           1
45210   cellular           0

[45211 rows x 2 columns]

In [89]:
imputacion = SimpleImputer(missing_values=2, strategy="most_frequent")  ## imputacion simple el mas frecuente

In [90]:
analisis.numcontact = imputacion.fit_transform(analisis[["numcontact"]])

In [91]:
analisis.numcontact[0]

0

In [92]:
analisis

age           job  numjob   marital  nummarital  education  \
0       58    management       4   married           1   tertiary   
1       44    technician       9    single           2  secondary   
2       33  entrepreneur       2   married           1  secondary   
3       47   blue-collar       1   married           1       None   
4       33          None      11    single           2       None   
...    ...           ...     ...       ...         ...        ...   
45206   51    technician       9   married           1   tertiary   
45207   71       retired       5  divorced           0    primary   
45208   72       retired       5   married           1  secondary   
45209   57   blue-collar       1   married           1  secondary   
45210   37  entrepreneur       2   married           1  secondary   

       numeducation default  numdefault  balance  ... numcontact  day month  \
0             2.000      no           0     2143  ...          0    5     5   
1             1.000      no           0       29  ...          0    5     5   
2             1.000      no           0        2  ...          0    5     5   
3             1.149      no           0     1506  ...          0    5     5   
4             1.149      no           0        1  ...          0    5     5   
...             ...     ...         ...      ...  ...        ...  ...   ...   
45206         2.000      no           0      825  ...          0   17    11   
45207         0.000      no           0     1729  ...          0   17    11   
45208         1.000      no           0     5715  ...          0   17    11   
45209         1.000      no           0      668  ...          1   17    11   
45210         1.000      no           0     2971  ...          0   17    11   

       duration campaign  pdays  previous  poutcome  numpoutcome  deposit  
0           261        1     -1         0      None          0.0       no  
1           151        1     -1         0      None          0.0       no  
2            76        1     -1         0      None          0.0       no  
3            92        1     -1         0      None          0.0       no  
4           198        1     -1         0      None          0.0       no  
...         ...      ...    ...       ...       ...          ...      ...  
45206       977        3     -1         0      None          0.0      yes  
45207       456        2     -1         0      None          0.0      yes  
45208      1127        5    184         3   success          2.0      yes  
45209       508        4     -1         0      None          0.0       no  
45210       361        2    188        11     other          1.0       no  

[45211 rows x 25 columns]

In [93]:
analisis.numcontact.value_counts()

numcontact
0    42305
1     2906
Name: count, dtype: int64

In [94]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45211 entries, 0 to 45210
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           45211 non-null  int64  
 1   job           44923 non-null  object 
 2   numjob        45211 non-null  int64  
 3   marital       45211 non-null  object 
 4   nummarital    45211 non-null  int64  
 5   education     43354 non-null  object 
 6   numeducation  45211 non-null  float64
 7   default       45211 non-null  object 
 8   numdefault    45211 non-null  int64  
 9   balance       45211 non-null  int64  
 10  housing       45211 non-null  object 
 11  numhousing    45211 non-null  int64  
 12  loan          45211 non-null  object 
 13  numloan       45211 non-null  int64  
 14  contact       32191 non-null  object 
 15  numcontact    45211 non-null  int64  
 16  day           45211 non-null  int64  
 17  month         45211 non-null  int64  
 18  duration      45211 non-null  i

============================================================

***Variable categorica completa***

In [1]:
import pandas as pd
import numpy as np

In [2]:
import sklearn
from sklearn.preprocessing import LabelEncoder  ###Codifique las etiquetas de destino con valores entre 0 y n_classes-1
from sklearn.impute import SimpleImputer  ### imputacion simple

In [3]:
url = "https://raw.githubusercontent.com/cristiandarioortegayubro/BA/main/Datasets/banco.csv"

In [4]:
analisis = pd.read_csv(url, index_col=0)
analisis.head(3)

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may       261         1     -1         0  unknown      no  
1  unknown    5   may       151         1     -1         0  unknown      no  
2  unknown    5   may        76         1     -1         0  unknown      no

In [5]:
analisis.job.value_counts()

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [6]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 6.2+ MB


In [7]:
analisis.replace({"unknown": None}, inplace=True) ### reemplazo el unknown por el None

In [8]:
analisis.head(3)

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   

  contact  day month  duration  campaign  pdays  previous poutcome deposit  
0    None    5   may       261         1     -1         0     None      no  
1    None    5   may       151         1     -1         0     None      no  
2    None    5   may        76         1     -1         0     None      no

In [9]:
analisis.job.value_counts().sum()

44923

In [10]:
analisis.job.isnull().sum()

288

In [11]:
convertir = LabelEncoder()

In [14]:
analisis.job = convertir.fit_transform(analisis[["job"]])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
analisis.job.value_counts()

job
1     9732
4     9458
9     7597
0     5171
7     4154
5     2264
6     1579
2     1487
10    1303
3     1240
8      938
11     288
Name: count, dtype: int64

In [16]:
analisis.job.value_counts().sum()

45211

In [17]:
imputacion = SimpleImputer(missing_values=11, strategy="mean")

In [18]:
analisis.job = imputacion.fit_transform(analisis[["job"]])

In [19]:
analisis.job.value_counts()

job
1.000000     9732
4.000000     9458
9.000000     7597
0.000000     5171
7.000000     4154
5.000000     2264
6.000000     1579
2.000000     1487
10.000000    1303
3.000000     1240
8.000000      938
4.297064      288
Name: count, dtype: int64

In [20]:
analisis.job.value_counts().sum()

45211