<p align="center">
<img src="https://numpy.org/images/logo.svg" width="80" height="">
</p>


https://numpy.org

 # **<font color="RoyalBlue">Generación de muestras aleatorias</font>**

<p align="justify">
✅ La generación de números aleatorios es fundamental en estadística y simulación de experimentos. <code>NumPy</code> proporciona una amplia gama de funciones en el módulo <code>numpy.random</code> para generar muestras aleatorias de diferentes distribuciones.
<br><br>
👀 A continuación, se presentan algunas distribuciones comunes y ejemplos de su aplicación:

<p align="justify"> 👀 Por convención, de esta manera se importa <code>Numpy</code>:  </p>

In [ ]:
import numpy as np

In [ ]:
import plotly.express as px

 ## **<font color="RoyalBlue">Distribución uniforme</font>**

<p align="justify">
✅ La distribución uniforme genera números aleatorios en un rango especificado con igual probabilidad. Esto puede ser útil para simular eventos donde todas las posibilidades son igualmente probables.
<br><br>
Por ejemplo, supongamos que queremos simular el lanzamiento de un dado:

```python
# Simular el lanzamiento de un dado
dado = np.random.randint(1, 7)  # Números aleatorios del 1 al 6

print("Resultado del lanzamiento del dado:", dado)
```


In [ ]:
# Simular el lanzamiento de un dado
dado = np.random.randint(1, 7)  # Números aleatorios del 1 al 6
dado

6

In [ ]:
dado = np.random.randint(1, 7)
dado

6

In [ ]:
dado = np.random.randint(1, 7)
dado

5

<p align="justify">
👀 Otro ejemplo, supongamos que queremos modelar la distribución de tiempos de espera de los clientes en una tienda, donde los clientes pueden llegar en cualquier momento dentro de un intervalo de tiempo específico.

In [ ]:
# Generar datos de tiempos de espera de los clientes (distribución uniforme)
tiempos_espera = np.random.uniform(low=0, high=30, size=1000)  # Tiempos de espera en minutos, de 0 a 30 minutos

In [ ]:
px.histogram(x=tiempos_espera,
             title="Distribución Uniforme de tiempos de espera de clientes",
             labels={"x":"Tiempo de Espera (minutos)"},
             template="gridon").update_layout(bargap=0.2)

In [ ]:
px.box(x=tiempos_espera,
       title="Distribución Uniforme de tiempos de espera de clientes",
       labels={"x":"Tiempo de Espera (minutos)"},
       template="gridon")

In [ ]:
px.ecdf(x=tiempos_espera,
        template="gridon",
        title = "Función de distribución acumulada",)

 ## **<font color="RoyalBlue">Distribución normal</font>**

✅ La distribución normal es una de las distribuciones más importantes en estadística y modelado de datos. Puede representar muchos fenómenos en la naturaleza y los negocios, como la altura de las personas o los ingresos de una población.
<br><br>
Por ejemplo, supongamos que queremos simular los ingresos anuales de una muestra de empleados de una empresa:

```python
# Simular ingresos anuales de una muestra de empleados
ingresos_anuales = np.random.normal(loc=50000, scale=10000, size=1000)

# 'loc' es la media de la distribución, 'scale' es la desviación estándar y 'size' es el tamaño de la muestra

print("Ingresos anuales simulados:", ingresos_anuales)
```


In [ ]:
# Simular ingresos anuales de una muestra de empleados
ingresos_anuales = np.random.normal(loc=90000, scale=10000, size=60).round(2)
ingresos_anuales

array([111475.04,  93629.34, 103296.58,  83715.05, 103510.82, 103364.57,
       105347.08,  96846.56,  94904.67,  96278.  ,  85129.37,  99741.49,
        77180.7 , 100103.49,  78537.63, 101622.64,  74201.64,  82431.73,
       105210.13,  94200.31,  96360.63,  72199.79, 106078.34,  89215.83,
        70565.94,  89691.06,  85658.63,  90648.09, 108038.62,  78273.74,
        82601.03,  87308.53,  88783.25,  77894.41,  90186.16,  86692.8 ,
        86719.21,  87536.67,  80697.62,  80471.12,  83130.38,  90719.46,
        98006.76,  89382.47,  93600.37,  89567.28,  88147.82,  88405.03,
        76616.35,  93099.85, 105487.53,  97367.53,  89365.21,  98393.8 ,
        85957.01,  82150.02,  89198.19,  95651.51, 102180.72,  85458.03])

👀 Cantidad de bins, regla de Sturges...

In [ ]:
int(1+np.log2(60))

6

In [ ]:
px.histogram(x=ingresos_anuales,
             title="Distribución ingresos anuales de empleados",
             labels={"x":"Ingresos anuales"},
             nbins=6,
             template="gridon").update_layout(bargap=0.2)

In [ ]:
px.box(x=ingresos_anuales,
       title="Distribución ingresos anuales de empleados",
       labels={"x":"Ingresos anuales"},
       template="gridon")

In [ ]:
px.ecdf(x=ingresos_anuales,
        template="gridon",
        title = "Función de distribución acumulada")

<p align="justify">
Otro ejemplo, supongamos que queremos modelar la distribución de la altura de los clientes de una tienda de camisas para determinar el tamaño promedio que deberíamos tener en stock....

In [ ]:
# Generar datos de altura de los clientes (distribución normal)
altura_clientes = np.random.normal(loc=170, scale=10, size=1000)

In [ ]:
int(1+np.log2(1000))

10

In [ ]:
px.histogram(x=altura_clientes,
             nbins=10,
             title="Distribución de altura de los clientes",
             labels={"x":"Altura (cm)"},
             template="gridon").update_layout(bargap=0.2)

In [ ]:
px.box(x=altura_clientes,
       title="Distribución de altura de los clientes",
       labels={"x":"Altura (cm)"},
       template="gridon")

In [ ]:
px.ecdf(x=altura_clientes,
        template="gridon",
        title = "Función de distribución acumulada")

 ## **<font color="RoyalBlue">Distribución binomial</font>**

<p align="justify">
✅ La distribución binomial modela el número de éxitos en una serie de ensayos independientes con una probabilidad de éxito constante.
<br><br>
Por ejemplo, supongamos que queremos simular el número de clientes que compran un producto en una tienda en línea durante una hora:

```python
# Simular el número de clientes que compran un producto en una tienda en línea durante una hora
num_clientes = np.random.binomial(n=100, p=0.1, size=1)

# 'n' es el número de ensayos, 'p' es la probabilidad de éxito y 'size' es el tamaño de la muestra

print("Número de clientes que compran un producto:", num_clientes)
```


In [ ]:
# Simular el número de clientes que compran un producto en una tienda en línea durante una hora
num_clientes = np.random.binomial(n=100, p=0.1, size=1)
num_clientes

array([5])

<p align="justify">
👀 Otro ejemplo, supongamos que queremos modelar la probabilidad de que un cliente realice una compra en una tienda en línea, donde la probabilidad de compra es del 30% y realizamos 100 intentos de compra...

In [ ]:
# Simular el número de clientes que compran un producto en una tienda en línea
num_clientes_compran = np.random.binomial(n=100, p=0.3, size=800)

In [ ]:
int(1+np.log2(800))

10

In [ ]:
px.histogram(x=num_clientes_compran,
             nbins=10,
             title="Número de clientes que compran un producto",
             labels={"x":"Número de Clientes que Compran"},
             template="gridon").update_layout(bargap=0.2)

In [ ]:
px.box(x=num_clientes_compran,
       title="Número de clientes que compran un producto",
       labels={"x":"Número de Clientes que Compran"},
       template="gridon")

In [ ]:
px.ecdf(x=num_clientes_compran,
        template="gridon",
        title = "Función de distribución acumulada")

 ## **<font color="RoyalBlue">Distribución de Poisson</font>**

<p align="justify">
✅ La distribución de Poisson modela el número de eventos que ocurren en un intervalo de tiempo o espacio fijo, dado que los eventos ocurren a una tasa constante e independientemente del tiempo o espacio.
<br><br>
Por ejemplo, supongamos que queremos simular el número de llamadas de servicio al cliente recibidas en una hora`

```python
# Simular el número de llamadas de servicio al cliente recibidas en una hora
num_llamadas = np.random.poisson(lam=10, size=1)

# 'lam' es la tasa de eventos y 'size' es el tamaño de la muestra

print("Número de llamadas de servicio al cliente:", num_llamadas)
```

In [ ]:
# Simular el número de llamadas de servicio al cliente recibidas en una hora
num_llamadas = np.random.poisson(lam=10, size=1)
num_llamadas

array([15])

<p align="justify">
👀 Otro ejemplo, supongamos que queremos modelar el número de llamadas de servicio al cliente recibidas en una hora, donde recibimos un promedio de 10 llamadas por hora.


In [ ]:
# Simular el número de llamadas de servicio al cliente recibidas en una hora
num_llamadas = np.random.poisson(lam=10, size=1000)

In [ ]:
int(1+np.log2(1000))

10

In [ ]:
px.histogram(x=num_llamadas,
             nbins=10,
             title="Distribución de Poisson de llamadas de Servicio al Cliente",
             labels={"x":"Número de llamadas"},
             template="gridon").update_layout(bargap=0.2)

In [ ]:
px.box(x=num_llamadas,
       title="Distribución de Poisson de llamadas de Servicio al Cliente",
       labels={"x":"Número de llamadas"},
       template="gridon")

In [ ]:
px.ecdf(x=num_llamadas,
        template="gridon",
        title = "Función de distribución acumulada")

 # **<font color="RoyalBlue">Cálculo de medidas de tendencia central y dispersión</font>**

<p align="justify">
✅ Las medidas de tendencia central y dispersión son fundamentales en estadística para resumir y comprender la distribución de los datos. NumPy proporciona funciones para calcular estas medidas de manera eficiente.
<br><br>
A continuación, se presenta cómo calcular y utilizar estas medidas en contextos empresariales:
</p>

 ## **<font color="RoyalBlue">Medidas de tendencia central</font>**

 ### **<font color="RoyalBlue">Media (Promedio)</font>**

<p align="justify">
✅ La media es la suma de todos los valores dividida por el número de valores. Es útil para calcular el valor promedio de un conjunto de datos. Por ejemplo, para calcular el promedio de las ventas mensuales de una empresa...

```python
# Ventas mensuales de una empresa en miles de dólares
ventas_mensuales = np.array([100, 120, 110, 130, 140])

# Calcular la media de las ventas mensuales
media_ventas = np.mean(ventas_mensuales)

print("Media de las ventas mensuales:", media_ventas)
```

In [ ]:
# Ventas mensuales de una empresa en miles de dólares
ventas_mensuales = np.array([100, 120, 110, 130, 140])
ventas_mensuales

array([100, 120, 110, 130, 140])

In [ ]:
# Calcular la media de las ventas mensuales
media_ventas = np.mean(ventas_mensuales)
media_ventas

120.0

 ### **<font color="RoyalBlue">Mediana</font>**

<p align="justify">
✅ La mediana es el valor que se encuentra en el centro de un conjunto de datos ordenados. Es útil cuando los datos están sesgados o tienen valores atípicos. Por ejemplo, para calcular la mediana de los ingresos anuales de una muestra de empleados...

```python
# Ingresos anuales de una muestra de empleados en miles de dólares
ingresos_anuales = np.array([40000, 50000, 60000, 70000, 80000])

# Calcular la mediana de los ingresos anuales
mediana_ingresos = np.median(ingresos_anuales)

print("Mediana de los ingresos anuales:", mediana_ingresos)
```


In [ ]:
# Ingresos anuales de una muestra de empleados en miles de dólares
ingresos_anuales = np.array([40000, 50000, 60000, 70000, 80000, 90000, 100000])
ingresos_anuales

array([ 40000,  50000,  60000,  70000,  80000,  90000, 100000])

In [ ]:
# Calcular la mediana de los ingresos anuales
mediana_ingresos = np.median(ingresos_anuales)
mediana_ingresos

70000.0

 ### **<font color="RoyalBlue">Moda</font>**

<p align="justify">
✅ La moda es el valor que aparece con mayor frecuencia en un conjunto de datos. Es útil para identificar patrones de comportamiento. Por ejemplo, para calcular la moda de los productos más vendidos en una tienda:

```python
# Número de ventas diarias de diferentes productos en una tienda
ventas_diarias = np.array([20, 30, 25, 25, 40, 30, 30, 25])

# Calcular la moda de las ventas diarias
moda_ventas = np.argmax(np.bincount(ventas_diarias))

print("Producto más vendido (moda):", moda_ventas)
```

In [ ]:
# Número de ventas diarias de diferentes productos en una tienda
ventas_diarias = np.array([20, 30, 25, 25, 40, 30, 30, 25, 40, 25, 30, 30, 45, 45, 30])
ventas_diarias

array([20, 30, 25, 25, 40, 30, 30, 25, 40, 25, 30, 30, 45, 45, 30])

In [ ]:
# Calcular la moda de las ventas diarias
moda_ventas = np.argmax(np.bincount(ventas_diarias))
moda_ventas

30

 ## **<font color="RoyalBlue">Medidas de dispersión</font>**

 ### **<font color="RoyalBlue">Varianza</font>**

<p align="justify">
✅ La varianza mide la dispersión de los datos con respecto a la media. Es útil para comprender la dispersión de los datos. Por ejemplo, para calcular la varianza de los tiempos de entrega de los pedidos de una empresa:

```python
# Tiempos de entrega de los pedidos en días
tiempos_entrega = np.array([2, 3, 2, 4, 3, 5, 2])

# Calcular la varianza de los tiempos de entrega
varianza_tiempos_entrega = np.var(tiempos_entrega)

print("Varianza de los tiempos de entrega:", varianza_tiempos_entrega)
```


In [ ]:
# Tiempos de entrega de los pedidos en días
tiempos_entrega = np.array([2, 3, 2, 4, 3, 5, 2, 5, 3, 6, 3, 2, 5, 4])
tiempos_entrega

array([2, 3, 2, 4, 3, 5, 2, 5, 3, 6, 3, 2, 5, 4])

In [ ]:
# Calcular la varianza de los tiempos de entrega
varianza_tiempos_entrega = np.var(tiempos_entrega)
varianza_tiempos_entrega.round(2)

1.68

 ### **<font color="RoyalBlue">Desviación estándar</font>**

<p align="justify">
✅ La desviación estándar es la raíz cuadrada de la varianza. Proporciona una medida de dispersión en la misma unidad que los datos originales. Por ejemplo, para calcular la desviación estándar de los precios de los productos en una tienda...

```python
# Precios de los productos en una tienda en dólares
precios_productos = np.array([20, 25, 30, 35, 40])

# Calcular la desviación estándar de los precios de los productos
desviacion_precios = np.std(precios_productos)

print("Desviación estándar de los precios de los productos:", desviacion_precios)
```

In [ ]:
# Precios de los productos en una tienda en dólares
precios_productos = np.array([20, 25, 30, 35, 40, 35, 40, 20])
precios_productos

array([20, 25, 30, 35, 40, 35, 40, 20])

In [ ]:
# Calcular la desviación estándar de los precios de los productos
desviacion_precios = np.std(precios_productos)
desviacion_precios.round(2)

7.68

<br>
<br>
<p align="center"><b>
💗
<font color="RoyalBlue">
Hemos llegado al final de nuestro colab, a seguir codeando en NumPy...
</font>
</p>
