<p align="center">
<img src="https://numpy.org/images/logo.svg" width="80" height="">
</p>


https://numpy.org

 # **<font color="RoyalBlue">Análisis de datos con Numpy</font>**

<p align="justify">
🔎 El análisis de datos con <code>NumPy</code> implica el extraer información valiosa de los conjuntos de datos. <code>NumPy</code> proporciona herramientas eficientes para manipular y analizar grandes cantidades de datos numéricos, lo que lo hace facilita el análisis de datos.
<br><br>
Con <code>NumPy</code>, se pueden realizar operaciones matemáticas y estadísticas avanzadas, como cálculos de promedios, desviaciones estándar, correlaciones y análisis de tendencias, que son fundamentales para comprender  rendimientos y tendencias del mercado. Además, <code>NumPy</code> permite la manipulación de arrays multidimensionales, lo que facilita la visualización y el procesamiento de datos complejos, como datos de ventas, finanzas, inventario y comportamiento del cliente.

<p align="justify"> 👀 Por convención, de esta manera se importa <code>Numpy</code>:  </p>

In [ ]:
import numpy as np

 # **<font color="RoyalBlue">Carga de datos en NumPy</font>**

<p align="justify">
La carga de datos es el primer paso en cualquier análisis de datos. NumPy proporciona varias funciones para cargar datos desde diferentes fuentes, como archivos CSV, TSV, TXT u otros formatos.
<br><br>
Estas son algunas de las formas comunes de cargar datos en NumPy:

 ## **<font color="RoyalBlue">Carga de datos desde archivos CSV</font>**

<p align="justify">
✅ La función <code>numpy.loadtxt()</code> se utiliza para cargar datos desde archivos CSV.
<br><br>
Por ejemplo, supongamos que tenemos un archivo llamado "DatosNumpy2.csv" con datos separados por comas:

```
 450.  343.  1200.  7876.  2887.
3837.  220.  3746.   897.  3487.
 987.  483.  9874.  6473.  8662.
5837.  614.  6846.  5239.  5958.
```

👀Podemos cargar estos datos en un array NumPy de la siguiente manera:



In [ ]:
url = "https://raw.githubusercontent.com/cristiandarioortegayubro/BDS/main/datasets/"
archivo = "DatosNumPy2.csv"

In [ ]:
data = np.loadtxt(url+archivo, delimiter=";")
data

array([[ 450.,  343., 1200., 7876., 2887.],
       [3837.,  220., 3746.,  897., 3487.],
       [ 987.,  483., 9874., 6473., 8662.],
       [5837.,  614., 6846., 5239., 5958.]])

<p align="justify">
✅ Se crea un array NumPy bidimensional donde cada fila representa una observación y cada columna representa una variable.

 ## **<font color="RoyalBlue">Carga de datos desde archivos TSV o TXT</font>**

<p align="justify">
✅ La función <code>numpy.loadtxt()</code> también se puede utilizar para cargar datos desde archivos de texto con diferentes delimitadores.
<br><br>
Por ejemplo, si tenemos un archivo llamado "DatosNumPy.tsv" con datos separados por tabulaciones:

```
 450.  343.  1200.  7876.  2887.
3837.  220.  3746.   897.  3487.
 987.  483.  9874.  6473.  8662.
5837.  614.  6846.  5239.  5958.
```

👀 Podemos cargar los datos de la misma manera que con un archivo CSV:


In [ ]:
url_tsv = "https://raw.githubusercontent.com/cristiandarioortegayubro/BDS/main/datasets/"
archivo_tsv = "DatosNumPy.tsv"

In [ ]:
data = np.loadtxt(url_tsv+archivo_tsv)
data

array([[ 450.,  343., 1200., 7876., 2887.],
       [3837.,  220., 3746.,  897., 3487.],
       [ 987.,  483., 9874., 6473., 8662.],
       [5837.,  614., 6846., 5239., 5958.]])

 ## **<font color="RoyalBlue">Manejo de datos faltantes</font>**

<p align="justify">
En algunos casos, los datos pueden tener valores faltantes representados por un valor especial, como "nan" (Not a Number) o "-999". NumPy proporciona opciones para manejar estos valores faltantes durante la carga de datos.
<br>

```
 450.        1200.  7876.  2887.
3837.  220.  3746.   897.  
 987.               6473.  8662.
       614.  6846.  5239.  5958.
```



👀 Por ejemplo, podemos especificar un valor de relleno utilizando el parámetro <code>filling_values</code>:

```python
data_with_missing = np.genfromtxt(url+archivo, delimiter=';', filling_values=-999)
```

In [ ]:
url = "https://raw.githubusercontent.com/cristiandarioortegayubro/BDS/main/datasets/"
archivo = "DatosFaltantesNumPy.csv"

In [ ]:
data_with_missing = np.genfromtxt(url+archivo, delimiter=';', filling_values=-999)
data_with_missing

array([[ 450., -999., 1200., 7876., 2887.],
       [3837.,  220., 3746.,  897., -999.],
       [ 987., -999., -999., 6473., 8662.],
       [-999.,  614., 6846., 5239., 5958.]])

In [ ]:
data_with_missing = np.genfromtxt(url+archivo, delimiter=';', filling_values=np.nan)
data_with_missing

array([[ 450.,   nan, 1200., 7876., 2887.],
       [3837.,  220., 3746.,  897.,   nan],
       [ 987.,   nan,   nan, 6473., 8662.],
       [  nan,  614., 6846., 5239., 5958.]])

In [ ]:
data_with_missing = np.genfromtxt(url+archivo, delimiter=';', filling_values="NaN")
data_with_missing

array([[ 450.,   nan, 1200., 7876., 2887.],
       [3837.,  220., 3746.,  897.,   nan],
       [ 987.,   nan,   nan, 6473., 8662.],
       [  nan,  614., 6846., 5239., 5958.]])

In [ ]:
data_with_missing = np.genfromtxt(url+archivo, delimiter=';', filling_values=None)
data_with_missing

array([[ 450.,   nan, 1200., 7876., 2887.],
       [3837.,  220., 3746.,  897.,   nan],
       [ 987.,   nan,   nan, 6473., 8662.],
       [  nan,  614., 6846., 5239., 5958.]])

 # **<font color="RoyalBlue">Filtrado y selección de datos</font>**

<p align="justify">
👀 Una vez que hemos cargado nuestros datos en arrays NumPy, a menudo necesitamos filtrar y seleccionar subconjuntos de datos basados en ciertas condiciones. NumPy proporciona varias formas de realizar esta tarea de manera eficiente.
<br><br>
A continuación, se presentan algunos ejemplos de filtrado y selección de datos:



 ## **<font color="RoyalBlue">Filtrado con expresiones booleanas</font>**

<p align="justify">
✅ Podemos utilizar expresiones booleanas para filtrar elementos de un array NumPy basados en ciertas condiciones. Por ejemplo, supongamos que tenemos un array de datos de cantidades de unidades de botellas estibadas en una bodega y queremos filtrar las distintas producciones que estén estibadas por encima de 30 días:
<br><br>
🍷 Este código muestra los productos estibados en una bodega que están por encima de 30 días de estiba.



In [ ]:
dias_estiba_productos = np.array([25, 31, 28, 35, 29, 33, 27])
dias_estiba_productos

array([25, 31, 28, 35, 29, 33, 27])

In [ ]:
mas_30_dias = dias_estiba_productos[dias_estiba_productos > 30]
mas_30_dias

array([31, 35, 33])

 ## **<font color="RoyalBlue">Filtrado con la función numpy.where()</font>**

<p align="justify">
✅ La función <code>numpy.where()</code> se puede utilizar para realizar filtrados más complejos. Por ejemplo, supongamos que queremos clasificar las diferentes cantidades de estibas en tres categorías:
<br><br>

- "joven" para cantidad de meses por debajo de 4,
- "crianza" para meses entre 4 y 36 meses, y
- "reserva" para meses por encima de 36.

<p align="justify">
<br>
🍷 Este código clasificará en las categorías correspondientes.



In [ ]:
meses_estiba_productos = np.array([2, 3, 5, 14, 2, 37, 54, 33, 22, 18, 4, 54])
meses_estiba_productos

array([ 2,  3,  5, 14,  2, 37, 54, 33, 22, 18,  4, 54])

In [ ]:
categorias = np.where(meses_estiba_productos <= 4, 'joven', np.where(meses_estiba_productos <= 36, 'crianza', 'reserva'))

In [ ]:
categorias

array(['joven', 'joven', 'crianza', 'crianza', 'joven', 'reserva',
       'reserva', 'crianza', 'crianza', 'crianza', 'joven', 'reserva'],
      dtype='<U7')

 ## **<font color="RoyalBlue">Selección de datos por índices</font>**

<p align="justify">
También podemos seleccionar subconjuntos de datos utilizando índices específicos.
<br><br>
👀 Por ejemplo, supongamos que queremos seleccionar los primeros tres elementos del array

In [ ]:
primeros_tres = categorias[:3]
primeros_tres

array(['joven', 'joven', 'crianza'], dtype='<U7')

👀 O queremos seleccionar los ultimos seis elementos del array

In [ ]:
ultimos_seis = meses_estiba_productos[-6:]
ultimos_seis

array([54, 33, 22, 18,  4, 54])

 # **<font color="RoyalBlue">Transformaciones de datos</font>**

<p align="justify">
Las transformaciones de datos son esenciales en el análisis de datos para preparar los datos de manera adecuada antes de realizar análisis estadísticos o entrenar modelos de aprendizaje automático.
<br><br>
A continuación, se presentan algunas transformaciones comunes de datos orientadas a negocios, junto con ejemplos específicos:

 ## **<font color="RoyalBlue">Normalización de datos</font>**

<p align="justify">
✅ La normalización es útil en casos donde queremos comparar variables que están en diferentes escalas. Por ejemplo, supongamos que tenemos datos de ventas y gastos mensuales en dos arrays separados y queremos comparar su rendimiento relativo:

```python
import numpy as np

# Datos de ventas mensuales en miles de dólares
ventas = np.array([100, 120, 110, 130, 140])

# Datos de gastos mensuales en miles de dólares
gastos = np.array([50, 60, 55, 65, 70])

# Normalización de datos
ventas_normalizadas = (ventas - np.min(ventas)) / (np.max(ventas) - np.min(ventas))
gastos_normalizados = (gastos - np.min(gastos)) / (np.max(gastos) - np.min(gastos))

print("Ventas normalizadas:", ventas_normalizadas)
print("Gastos normalizados:", gastos_normalizados)
```



In [ ]:
# Datos de ventas mensuales en miles de dólares
ventas = np.array([100, 120, 110, 130, 140])
ventas

array([100, 120, 110, 130, 140])

In [ ]:
# Datos de gastos mensuales en miles de dólares
gastos = np.array([50, 60, 55, 65, 70])
gastos

array([50, 60, 55, 65, 70])

In [ ]:
# Normalización de datos
ventas_normalizadas = (ventas - np.min(ventas)) / (np.max(ventas) - np.min(ventas))
gastos_normalizados = (gastos - np.min(gastos)) / (np.max(gastos) - np.min(gastos))

In [ ]:
ventas_normalizadas

array([0.  , 0.5 , 0.25, 0.75, 1.  ])

In [ ]:
gastos_normalizados

array([0.  , 0.5 , 0.25, 0.75, 1.  ])

 ## **<font color="RoyalBlue">Estandarización de datos</font>**

<p align="justify">
✅ La estandarización es útil cuando queremos comparar variables que tienen diferentes distribuciones. Por ejemplo, supongamos que tenemos datos de puntajes de satisfacción del cliente en una escala del 1 al 10 y queremos estandarizarlos para compararlos con otros indicadores:

```python
# Datos de puntajes de satisfacción del cliente
satisfaccion_cliente = np.array([7, 8, 6, 9, 7])

# Estandarización de datos
satisfaccion_estandarizada = (satisfaccion_cliente - np.mean(satisfaccion_cliente)) / np.std(satisfaccion_cliente)

print("Satisfacción del cliente estandarizada:", satisfaccion_estandarizada)
```



In [ ]:
# Datos de puntajes de satisfacción del cliente
satisfaccion_cliente = np.array([7, 8, 6, 9, 7])
satisfaccion_cliente

array([7, 8, 6, 9, 7])

In [ ]:
# Estandarización de datos
satisfaccion_estandarizada = (satisfaccion_cliente - np.mean(satisfaccion_cliente)) / np.std(satisfaccion_cliente)
satisfaccion_estandarizada

array([-0.39223227,  0.58834841, -1.37281295,  1.56892908, -0.39223227])

 ## **<font color="RoyalBlue">Discretización de datos</font>**

<p align="justify">
✅ La discretización es útil cuando queremos agrupar datos continuos en categorías discretas. Por ejemplo, supongamos que tenemos datos de ingresos anuales y queremos discretizarlos en categorías de ingresos:

```python
# Datos de ingresos anuales en miles de dólares
ingresos = np.array([250, 300, 200, 350, 400])

# Discretización de datos
categorias_ingresos = np.digitize(ingresos, bins=[0, 200, 300, np.inf], right=True)
categorias_label = ['Bajo', 'Medio', 'Alto']

ingresos_categorizados = [categorias_label[i-1] for i in categorias_ingresos]

print("Ingresos categorizados:", ingresos_categorizados)
```


In [ ]:
# Datos de ingresos anuales en miles de dólares
ingresos = np.array([250, 300, 200, 350, 400])
ingresos

array([250, 300, 200, 350, 400])

In [ ]:
# Discretización de datos
categorias_ingresos = np.digitize(ingresos, bins=[0, 200, 300, np.inf], right=True)
categorias_label = ['Bajo', 'Medio', 'Alto']

In [ ]:
ingresos_categorizados = [categorias_label[i-1] for i in categorias_ingresos]
ingresos_categorizados

['Medio', 'Medio', 'Bajo', 'Alto', 'Alto']

 # **<font color="RoyalBlue">Ejercicios prácticos</font>**

<p align="justify">
✅ A continuación, se presentan algunos ejercicios prácticos para aplicar los conceptos de este colab:
<br><br>


🏷 **a. Ejercicio 1: Normalización de Datos de Ventas y Gastos:**
   - Supongamos que tenemos datos de ventas mensuales en miles de dólares y datos de gastos mensuales en miles de dólares para una empresa. Normaliza ambos conjuntos de datos y calcula el margen de beneficio (ventas - gastos) para cada mes.

```python
# Datos de ventas mensuales en miles de dólares
ventas = np.array([100, 120, 110, 130, 140])

# Datos de gastos mensuales en miles de dólares
gastos = np.array([50, 60, 55, 65, 70])
```

🏷 **b. Ejercicio 2: Estandarización de Datos de Satisfacción del Cliente:**
   - Supongamos que tenemos datos de puntajes de satisfacción del cliente en una escala del 1 al 10 para una empresa. Estandariza estos datos y calcula el promedio de satisfacción del cliente.

```python
# Datos de puntajes de satisfacción del cliente
satisfaccion_cliente = np.array([7, 8, 6, 9, 7])
```

🏷 **c. Ejercicio 3: Discretización de Datos de Ingresos Anuales:**
   - Supongamos que tenemos datos de ingresos anuales en miles de dólares para una empresa. Discretiza estos datos en tres categorías: "bajo", "medio" y "alto" ingresos.

```python
# Datos de ingresos anuales en miles de dólares
ingresos = np.array([250, 300, 200, 350, 400])

```



<p align="justify">
<br>
✅ A continuación, las soluciones sugeridas:
<br><br>


🏷 **a. Ejercicio 1: Normalización de Datos de Ventas y Gastos:**
   - Supongamos que tenemos datos de ventas mensuales en miles de dólares y datos de gastos mensuales en miles de dólares para una empresa. Normaliza ambos conjuntos de datos y calcula el margen de beneficio (ventas - gastos) para cada mes.

```python
# Datos de ventas mensuales en miles de dólares
ventas = np.array([100, 120, 110, 130, 140])

# Datos de gastos mensuales en miles de dólares
gastos = np.array([50, 60, 55, 65, 70])

# Normalización de datos
ventas_normalizadas = (ventas - np.min(ventas)) / (np.max(ventas) - np.min(ventas))
gastos_normalizados = (gastos - np.min(gastos)) / (np.max(gastos) - np.min(gastos))

# Cálculo del margen de beneficio
margen_beneficio = ventas_normalizadas - gastos_normalizadas

print("Margen de beneficio:", margen_beneficio)
```

🏷 **b. Ejercicio 2: Estandarización de Datos de Satisfacción del Cliente:**
   - Supongamos que tenemos datos de puntajes de satisfacción del cliente en una escala del 1 al 10 para una empresa. Estandariza estos datos y calcula el promedio de satisfacción del cliente.

```python
# Datos de puntajes de satisfacción del cliente
satisfaccion_cliente = np.array([7, 8, 6, 9, 7])

# Estandarización de datos
satisfaccion_estandarizada = (satisfaccion_cliente - np.mean(satisfaccion_cliente)) / np.std(satisfaccion_cliente)

# Cálculo del promedio de satisfacción del cliente
promedio_satisfaccion = np.mean(satisfaccion_estandarizada)

print("Promedio de satisfacción del cliente:", promedio_satisfaccion)
```

🏷 **c. Ejercicio 3: Discretización de Datos de Ingresos Anuales:**
   - Supongamos que tenemos datos de ingresos anuales en miles de dólares para una empresa. Discretiza estos datos en tres categorías: "bajo", "medio" y "alto" ingresos.

```python
# Datos de ingresos anuales en miles de dólares
ingresos = np.array([250, 300, 200, 350, 400])

# Discretización de datos
categorias_ingresos = np.digitize(ingresos, bins=[0, 200, 300, np.inf], right=True)
categorias_label = ['Bajo', 'Medio', 'Alto']

ingresos_categorizados = [categorias_label[i-1] for i in categorias_ingresos]

print("Ingresos categorizados:", ingresos_categorizados)
```

<br>
<br>
<p align="center"><b>
💗
<font color="RoyalBlue">
Hemos llegado al final de nuestro colab, a seguir codeando en NumPy...
</font>
</p>
